export const Questions = [
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        optionA: "Bolivia",
        optionB: "Uruguay",
        optionC: "Argentina",
        optionD: "Chile",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
        optionA: "Uruguay",
        optionB: "Venezuela",
        optionC: "Chile",
        optionD: "Brasil",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg",
        optionA: "Perú",
        optionB: "Uruguay",
        optionC: "Venezuela",
        optionD: "Bolivia",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
        optionA: "Antigua y Barbuda",
        optionB: "Venezuela",
        optionC: "Guatemala",
        optionD: "Brasil",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
        optionA: "Belice",
        optionB: "Barbados",
        optionC: "Bahamas",
        optionD: "Guatemala",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg",
        optionA: "México",
        optionB: "Granada",
        optionC: "Cuba",
        optionD: "Brasil",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
        optionA: "Nicaragua",
        optionB: "Haití",
        optionC: "Cuba",
        optionD: "Honduras",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg",
        optionA: "Paraguay",
        optionB: "El Salvador",
        optionC: "Cuba",
        optionD: "Chile",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg",
        optionA: "Cuba",
        optionB: "Honduras",
        optionC: "Costa Rica",
        optionD: "Ecuador",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Bandera_de_Granada_%28Granada%29.svg",
        optionA: "Jamaica",
        optionB: "Panamá",
        optionC: "Guatemala",
        optionD: "Granada",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
        optionA: "México",
        optionB: "Dominica",
        optionC: "República Dominicana",
        optionD: "Nicaragua",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg",
        optionA: "Colombia",
        optionB: "San Vicente y las Granadinas",
        optionC: "Argentina",
        optionD: "El Salvador",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg",
        optionA: "Honduras",
        optionB: "Venezuela",
        optionC: "Colombia",
        optionD: "Panamá",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
        optionA: "Granada",
        optionB: "Antigua y Barbuda",
        optionC: "San Cristóbal y Nieves",
        optionD: "Santa Lucía",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
        optionA: "Chile",
        optionB: "Ecuador",
        optionC: "Cuba",
        optionD: "Perú",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
        optionA: "Guyana",
        optionB: "San Vicente y las Granadinas",
        optionC: "Jamaica",
        optionD: "Nicaragua",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg",
        optionA: "Surinam",
        optionB: "San Vicente y las Granadinas",
        optionC: "Guyana",
        optionD: "Belice",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg",
        optionA: "El Salvador",
        optionB: "Argentina",
        optionC: "Guatemala",
        optionD: "Nicaragua",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
        optionA: "Paraguay",
        optionB: "Colombia",
        optionC: "Venezuela",
        optionD: "Bolivia",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
        optionA: "República Dominicana",
        optionB: "Cuba",
        optionC: "Costa Rica",
        optionD: "Dominica",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
        optionA: "Barbados",
        optionB: "Trinidad y Tobago",
        optionC: "Granada",
        optionD: "Belice",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg",
        optionA: "Perú",
        optionB: "Honduras",
        optionC: "Bahamas",
        optionD: "Panamá",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
        optionA: "Honduras",
        optionB: "Chile",
        optionC: "Jamaica",
        optionD: "Cuba",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
        optionA: "Barbados",
        optionB: "Surinam",
        optionC: "Dominica",
        optionD: "Santa Lucía",
        asnwer: "optionC",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg",
        optionA: "El Salvador",
        optionB: "Guatemala",
        optionC: "Nicaragua",
        optionD: "Argentina",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
        optionA: "Bahamas",
        optionB: "Guatemala",
        optionC: "Santa Lucía",
        optionD: "Barbados",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg",
        optionA: "Costa Rica",
        optionB: "Panamá",
        optionC: "Haití",
        optionD: "Belice",
        asnwer: "optionD",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
        optionA: "Santa Lucía",
        optionB: "Surinam",
        optionC: "Trinidad y Tobago",
        optionD: "Antigua y Barbuda",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg",
        optionA: "Brasil",
        optionB: "Guyana",
        optionC: "Nicaragua",
        optionD: "Granada",
        asnwer: "optionB",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
        optionA: "Ecuador",
        optionB: "Colombia",
        optionC: "Venezuela",
        optionD: "Bolivia",
        asnwer: "optionA",
    },
    {
        urlImg: "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg",
        optionA: "Belice",
        optionB: "Surinam",
        optionC: "Barbados",
        optionD: "Honduras",
        asnwer: "optionD",
    },
  ];